<a href="https://colab.research.google.com/github/arizomo/Numpy/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [6]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [9]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [12]:
a[3:7]

array([ 4, 30, 51,  7])

In [14]:
a[1::4]

array([30, 51, 40])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
type(np.ones(()))

numpy.ndarray

In [25]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])